# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dinesh Yadav
tageline:         'blog'
description:      'My daily sprinkles on life and technology'
url:              http://hyde.getpoole.com
baseurl:          https://github.com/

author:
  name:           'Dinesh Yadav'
  url:            https://twitter.com/dinesh_oi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dinesh
